### ISSUE TITLE
 maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by aojielian** [FunctionLab/sei-framework#8]
hi,
when i run pipeline.sh, i got this error "maximum recursion depth exceeded while calling a Python object"
how can i fix it?

Thanks

**Comment by aojielian** [comment]
$ sh run_pipeline.sh /Users/aojie/ebc963fe-cf43-4063-aa31-33183904d3b2_Joon_Yong.Ryan_Yuen.Goldmann.Netherlands_Consortium.allpromoter.hg38.vcf hg38 test-output
use_cuda: False
Traceback (most recent call last):
  File "sequence_class.py", line 171, in <module>
    os.path.join(results_dir, "sequence_class_scores.tsv"))
  File "sequence_class.py", line 104, in write_to_tsv
    cp_df.drop_duplicates(subset=check_columns, inplace=True)
  File "/Users/aojie/opt/anaconda3/envs/selene-cpu/lib/python3.6/site-packages/pandas/core/frame.py", line 3098, in drop_duplicates
    duplicated = self.duplicated(subset, keep=keep)
  File "/Users/aojie/opt/anaconda3/envs/selene-cpu/lib/python3.6/site-packages/pandas/core/frame.py", line 3146, in duplicated
    ids = get_group_index(labels, shape, sort=False, xnull=False)
  File "/Users/aojie/opt/anaconda3/envs/selene-cpu/lib/python3.6/site-packages/pandas/core/sorting.py", line 94, in get_group_index
    return loop(list(labels), list(shape))
  File "/Users/aojie/opt/anaconda3/envs/selene-cpu/lib/python3.6/site-packages/pandas/core/sorting.py", line 85, in loop
    return loop(labels, shape)
  File "/Users/aojie/opt/anaconda3/envs/selene-cpu/lib/python3.6/site-packages/pandas/core/sorting.py", line 85, in loop
    return loop(labels, shape)
  File "/Users/aojie/opt/anaconda3/envs/selene-cpu/lib/python3.6/site-packages/pandas/core/sorting.py", line 85, in loop
    return loop(labels, shape)
  [Previous line repeated 988 more times]
  File "/Users/aojie/opt/anaconda3/envs/selene-cpu/lib/python3.6/site-packages/pandas/core/sorting.py", line 59, in loop
    stride = np.prod(shape[1:nlev], dtype='i8')
  File "/Users/aojie/opt/anaconda3/envs/selene-cpu/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 2585, in prod
    initial=initial)
  File "/Users/aojie/opt/anaconda3/envs/selene-cpu/lib/python3.6/site-packages/numpy/core/fromnumeric.py", line 70, in _wrapreduction
    if type(obj) is not mu.ndarray:
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by jzthree** [comment]
This looks like a pandas issue to me. Can you try updating / reinstalling pandas?

**Comment by kathyxchen** [comment]
Marking this as closed, but yes updating pandas generally fixes the issue
